/**
 * world-atlas(Natural Earth) 나라 영어 이름 → 교과서에서 쓰는 한국어 이름입니다.
 * 이름은 외교부·교과서 표기를 따르고, 목록에 없으면 영어 이름을 그대로 보여 줍니다.
 */
export const koreanCountryNames: Record<string, string> = {
  "Afghanistan": "아프가니스탄", "Akrotiri": "아크로티리", "Åland": "올란드 제도", "Albania": "알바니아", "Algeria": "알제리",
  "American Samoa": "아메리칸사모아", "Andorra": "안도라", "Angola": "앙골라", "Anguilla": "앵귈라", "Antarctica": "남극 대륙",
  "Antigua and Barb.": "앤티가 바부다", "Argentina": "아르헨티나", "Armenia": "아르메니아", "Aruba": "아루바",
  "Ashmore and Cartier Is.": "애시모어 카르티에 제도", "Australia": "오스트레일리아", "Austria": "오스트리아", "Azerbaijan": "아제르바이잔",
  "Bahamas": "바하마", "Bahrain": "바레인", "Baikonur": "바이코누르", "Bajo Nuevo Bank": "바호 누에보 뱅크", "Bangladesh": "방글라데시",
  "Barbados": "바베이도스", "Belarus": "벨라루스", "Belgium": "벨기에", "Belize": "벨리즈", "Benin": "베냉", "Bermuda": "버뮤다",
  "Bhutan": "부탄", "Bolivia": "볼리비아", "Bosnia and Herz.": "보스니아 헤르체고비나", "Botswana": "보츠와나",
  "Br. Indian Ocean Ter.": "영국령 인도양 지역", "Brazil": "브라질", "British Virgin Is.": "영국령 버진아일랜드", "Brunei": "브루나이",
  "Bulgaria": "불가리아", "Burkina Faso": "부르키나파소", "Burundi": "부룬디", "Cabo Verde": "카보베르데", "Cambodia": "캄보디아",
  "Cameroon": "카메룬", "Canada": "캐나다", "Cayman Is.": "케이맨 제도", "Central African Rep.": "중앙아프리카 공화국", "Chad": "차드",
  "Chile": "칠레", "China": "중국", "Clipperton I.": "클리퍼턴섬", "Colombia": "콜롬비아", "Comoros": "코모로", "Congo": "콩고",
  "Cook Is.": "쿡 제도", "Coral Sea Is.": "코럴해 제도", "Costa Rica": "코스타리카", "Côte d'Ivoire": "코트디부아르", "Croatia": "크로아티아",
  "Cuba": "쿠바", "Curaçao": "퀴라소", "Cyprus": "키프로스", "Cyprus U.N. Buffer Zone": "키프로스 완충 지대", "Czechia": "체코",
  "Dem. Rep. Congo": "콩고 민주 공화국", "Denmark": "덴마크", "Dhekelia": "데켈리아", "Djibouti": "지부티", "Dominica": "도미니카 연방",
  "Dominican Rep.": "도미니카 공화국", "Ecuador": "에콰도르", "Egypt": "이집트", "El Salvador": "엘살바도르", "Eq. Guinea": "적도 기니",
  "Eritrea": "에리트레아", "Estonia": "에스토니아", "eSwatini": "에스와티니", "Ethiopia": "에티오피아", "Faeroe Is.": "페로 제도",
  "Falkland Is.": "포클랜드 제도", "Fiji": "피지", "Finland": "핀란드", "Fr. Polynesia": "프랑스령 폴리네시아",
  "Fr. S. Antarctic Lands": "프랑스령 남방 지역", "France": "프랑스", "Gabon": "가봉", "Gambia": "감비아", "Georgia": "조지아",
  "Germany": "독일", "Ghana": "가나", "Gibraltar": "지브롤터", "Greece": "그리스", "Greenland": "그린란드", "Grenada": "그레나다",
  "Guam": "괌", "Guatemala": "과테말라", "Guernsey": "건지섬", "Guinea": "기니", "Guinea-Bissau": "기니비사우", "Guyana": "가이아나",
  "Haiti": "아이티", "Heard I. and McDonald Is.": "허드 맥도널드 제도", "Honduras": "온두라스", "Hong Kong": "홍콩", "Hungary": "헝가리",
  "Iceland": "아이슬란드", "India": "인도", "Indian Ocean Ter.": "오스트레일리아령 인도양 지역", "Indonesia": "인도네시아", "Iran": "이란",
  "Iraq": "이라크", "Ireland": "아일랜드", "Isle of Man": "맨섬", "Israel": "이스라엘", "Italy": "이탈리아", "Jamaica": "자메이카",
  "Japan": "일본", "Jersey": "저지섬", "Jordan": "요르단", "Kazakhstan": "카자흐스탄", "Kenya": "케냐", "Kiribati": "키리바시",
  "Kosovo": "코소보", "Kuwait": "쿠웨이트", "Kyrgyzstan": "키르기스스탄", "Laos": "라오스", "Latvia": "라트비아", "Lebanon": "레바논",
  "Lesotho": "레소토", "Liberia": "라이베리아", "Libya": "리비아", "Liechtenstein": "리히텐슈타인", "Lithuania": "리투아니아",
  "Luxembourg": "룩셈부르크", "Macao": "마카오", "Macedonia": "북마케도니아", "Madagascar": "마다가스카르", "Malawi": "말라위",
  "Malaysia": "말레이시아", "Maldives": "몰디브", "Mali": "말리", "Malta": "몰타", "Marshall Is.": "마셜 제도", "Mauritania": "모리타니",
  "Mauritius": "모리셔스", "Mexico": "멕시코", "Micronesia": "미크로네시아", "Moldova": "몰도바", "Monaco": "모나코", "Mongolia": "몽골",
  "Montenegro": "몬테네그로", "Montserrat": "몬트세랫", "Morocco": "모로코", "Mozambique": "모잠비크", "Myanmar": "미얀마",
  "N. Cyprus": "북키프로스", "N. Mariana Is.": "북마리아나 제도", "Namibia": "나미비아", "Nauru": "나우루", "Nepal": "네팔",
  "Netherlands": "네덜란드", "New Caledonia": "뉴칼레도니아", "New Zealand": "뉴질랜드", "Nicaragua": "니카라과", "Niger": "니제르",
  "Nigeria": "나이지리아", "Niue": "니우에", "Norfolk Island": "노퍽섬", "North Korea": "북한", "Norway": "노르웨이", "Oman": "오만",
  "Pakistan": "파키스탄", "Palau": "팔라우", "Palestine": "팔레스타인", "Panama": "파나마", "Papua New Guinea": "파푸아 뉴기니",
  "Paraguay": "파라과이", "Peru": "페루", "Philippines": "필리핀", "Pitcairn Is.": "핏케언 제도", "Poland": "폴란드", "Portugal": "포르투갈",
  "Puerto Rico": "푸에르토리코", "Qatar": "카타르", "Romania": "루마니아", "Russia": "러시아", "Rwanda": "르완다",
  "S. Geo. and the Is.": "사우스조지아 사우스샌드위치 제도", "S. Sudan": "남수단", "Saint Helena": "세인트헬레나", "Saint Lucia": "세인트루시아",
  "Samoa": "사모아", "San Marino": "산마리노", "São Tomé and Principe": "상투메 프린시페", "Saudi Arabia": "사우디아라비아",
  "Scarborough Reef": "스카버러 암초", "Senegal": "세네갈", "Serbia": "세르비아", "Serranilla Bank": "세라니야 뱅크", "Seychelles": "세이셸",
  "Siachen Glacier": "시아첸 빙하", "Sierra Leone": "시에라리온", "Singapore": "싱가포르", "Sint Maarten": "신트마르턴", "Slovakia": "슬로바키아",
  "Slovenia": "슬로베니아", "Solomon Is.": "솔로몬 제도", "Somalia": "소말리아", "Somaliland": "소말릴란드", "South Africa": "남아프리카 공화국",
  "South Korea": "대한민국", "Spain": "에스파냐", "Spratly Is.": "스프래틀리 군도", "Sri Lanka": "스리랑카", "St-Barthélemy": "생바르텔레미",
  "St-Martin": "생마르탱", "St. Kitts and Nevis": "세인트키츠 네비스", "St. Pierre and Miquelon": "생피에르 미클롱",
  "St. Vin. and Gren.": "세인트빈센트 그레나딘", "Sudan": "수단", "Suriname": "수리남", "Sweden": "스웨덴", "Switzerland": "스위스",
  "Syria": "시리아", "Taiwan": "타이완", "Tajikistan": "타지키스탄", "Tanzania": "탄자니아", "Thailand": "태국", "Timor-Leste": "동티모르",
  "Togo": "토고", "Tonga": "통가", "Trinidad and Tobago": "트리니다드 토바고", "Tunisia": "튀니지", "Turkey": "튀르키예",
  "Turkmenistan": "투르크메니스탄", "Turks and Caicos Is.": "터크스 케이커스 제도", "Tuvalu": "투발루", "U.S. Minor Outlying Is.": "미국령 군소 제도",
  "U.S. Virgin Is.": "미국령 버진아일랜드", "Uganda": "우간다", "Ukraine": "우크라이나", "United Arab Emirates": "아랍 에미리트",
  "United Kingdom": "영국", "United States of America": "미국", "Uruguay": "우루과이", "USNB Guantanamo Bay": "관타나모 미 해군 기지",
  "Uzbekistan": "우즈베키스탄", "Vanuatu": "바누아투", "Vatican": "바티칸", "Venezuela": "베네수엘라", "Vietnam": "베트남",
  "W. Sahara": "서사하라", "Wallis and Futuna Is.": "왈리스 푸투나", "Yemen": "예멘", "Zambia": "잠비아", "Zimbabwe": "짐바브웨",
};

export const countryKoreanName = (name: string) => koreanCountryNames[name] ?? name;
