import { topicWords as words, type CultureTopic } from "@/features/culture/core";

/* 중국문화 수업의 주제 자료입니다. 고등학교 중국문화 교과에서 흔히 다루는 사실만 직접 적었습니다.
 * 중국어에는 {汉字|hàn zì} 표기로 병음을 답니다. 병음은 음절마다 띄어 쓰고 경성은 부호 없이 씁니다. */

export const chinaCategories = { festivals: "명절", food: "음식·차", life: "생활·예절", tradition: "전통 문화", heritage: "역사·유산", regions: "지역·언어" } as const;

export const CHINA_TOPICS: CultureTopic[] = [
  {
    id: "chunjie", category: "festivals", title: "춘절(설)", native: "{春节|Chūn Jié}", when: "음력 1월 1일",
    summary: "중국에서 가장 큰 명절로 음력 1월 1일입니다. 섣달그믐부터 가족이 모여 새해를 맞고, 며칠 동안 법정 휴일이 이어집니다.",
    points: ["섣달그믐(除夕) 밤에 온 가족이 모여 年夜饭(섣달그믐 저녁 식사)을 먹습니다. 북쪽 지역에서는 饺子(교자)를 빚어 먹습니다.", "문에 새해 문구인 春联을 붙이고, 福 자를 거꾸로 붙이기도 합니다. ‘거꾸로(倒)’와 ‘온다(到)’의 발음이 dào로 같아 ‘복이 온다’는 뜻이 됩니다.", "어른이 아이에게 붉은 봉투에 넣은 세뱃돈 红包를 줍니다.", "폭죽을 터뜨리는 풍습이 있지만, 요즘은 많은 도시에서 폭죽을 제한합니다."],
    words: words("春节/chūn jié/설|除夕/chú xī/섣달그믐|饺子/jiǎo zi/교자(만두)|红包/hóng bāo/붉은 봉투(세뱃돈)|春联/chūn lián/새해에 문에 붙이는 대련"),
    phrase: { native: "{新年快乐|xīn nián kuài lè}!", ko: "새해 복 많이 받으세요!" },
    local: "음력 1월 1일, 年夜饭·饺子·红包·春联", korea: "음력 1월 1일(설날), 차례·세배·떡국·세뱃돈",
    quiz: [{ statement: "중국의 춘절은 양력 1월 1일이다.", answer: false, note: "음력 1월 1일입니다. 양력 1월 1일은 元旦이라고 합니다." }, { statement: "춘절에 붉은 봉투에 넣어 주는 세뱃돈을 红包라고 한다.", answer: true }],
    think: "한국의 설날과 중국의 춘절에서 비슷한 점과 다른 점은 무엇일까요?",
  },
  {
    id: "yuanxiao", category: "festivals", title: "원소절", native: "{元宵节|Yuán xiāo Jié}", when: "음력 1월 15일",
    summary: "새해 첫 보름날로, 춘절 명절을 마무리하는 날입니다.",
    points: ["등불을 달고 구경하며, 등불에 적힌 수수께끼를 푸는 猜灯谜 놀이를 합니다.", "찹쌀 경단 元宵를 먹습니다. 남쪽 지역에서는 汤圆이라고도 부릅니다."],
    words: words("元宵/yuán xiāo/찹쌀 경단|汤圆/tāng yuán/찹쌀 경단(남쪽 이름)|灯笼/dēng long/등롱|猜灯谜/cāi dēng mí/등불 수수께끼 풀기"),
    local: "음력 1월 15일, 등불 구경·元宵", korea: "정월대보름(음력 1월 15일), 부럼·오곡밥·달맞이",
    quiz: [{ statement: "원소절에는 찹쌀 경단을 먹는다.", answer: true }, { statement: "원소절은 음력 8월 15일이다.", answer: false, note: "음력 1월 15일입니다. 음력 8월 15일은 중추절입니다." }],
    think: "정월대보름과 원소절의 풍습을 비교해 봅시다.",
  },
  {
    id: "qingming", category: "festivals", title: "청명절", native: "{清明节|Qīng míng Jié}", when: "양력 4월 5일 무렵",
    summary: "24절기의 하나이자 조상의 묘를 찾아 돌보는 날로, 법정 공휴일입니다.",
    points: ["조상의 묘를 찾아 청소하고 제사를 지내는 것을 扫墓라고 합니다.", "봄나들이(踏青)를 가고 연을 날리기도 합니다.", "절기라서 양력으로 날짜가 거의 일정합니다."],
    words: words("扫墓/sǎo mù/성묘|踏青/tà qīng/봄나들이|风筝/fēng zheng/연"),
    local: "양력 4월 5일 무렵, 扫墓·踏青", korea: "한식(4월 5일 무렵)에 성묘",
    quiz: [{ statement: "청명절에는 조상의 묘를 찾아 돌본다.", answer: true }, { statement: "청명절 날짜는 음력으로 정한다.", answer: false, note: "24절기라서 양력 4월 5일 무렵으로 거의 일정합니다." }],
    think: "청명절과 한국의 한식은 어떤 점이 비슷할까요?",
  },
  {
    id: "duanwu", category: "festivals", title: "단오절", native: "{端午节|Duān wǔ Jié}", when: "음력 5월 5일",
    summary: "초나라 시인 屈原(굴원)을 기리는 데서 비롯되었다고 전해지는 명절입니다.",
    points: ["용 모양 배로 경주하는 赛龙舟를 합니다.", "댓잎에 찹쌀을 싸서 찐 粽子를 먹습니다."],
    words: words("粽子/zòng zi/댓잎에 싼 찹쌀밥|龙舟/lóng zhōu/용 모양 배|屈原/Qū Yuán/굴원(초나라 시인)"),
    local: "음력 5월 5일, 용선 경주·粽子", korea: "단오(음력 5월 5일), 창포물에 머리 감기·씨름·그네뛰기, 강릉 단오제",
    quiz: [{ statement: "단오절에는 용 모양 배로 경주를 한다.", answer: true }, { statement: "粽子는 밀가루로 빚은 만두이다.", answer: false, note: "댓잎에 찹쌀을 싸서 찐 음식입니다." }],
    think: "같은 날인 한국의 단오와 중국의 단오절은 무엇이 다를까요?",
  },
  {
    id: "zhongqiu", category: "festivals", title: "중추절", native: "{中秋节|Zhōng qiū Jié}", when: "음력 8월 15일",
    summary: "보름달을 보며 가족이 모이는 명절입니다. 둥근 달은 가족이 함께 모이는 것(团圆)을 뜻합니다.",
    points: ["둥근 과자 月饼을 나누어 먹으며 달구경(赏月)을 합니다.", "달에 사는 선녀 嫦娥(항아)의 이야기가 전해집니다."],
    words: words("月饼/yuè bǐng/월병|赏月/shǎng yuè/달구경|团圆/tuán yuán/한자리에 모임"),
    phrase: { native: "{中秋节快乐|Zhōng qiū Jié kuài lè}!", ko: "즐거운 중추절 보내세요!" },
    local: "음력 8월 15일, 月饼·달구경", korea: "추석(음력 8월 15일), 송편·차례·성묘",
    quiz: [{ statement: "중추절에는 월병을 먹는다.", answer: true }, { statement: "중추절의 둥근 달은 헤어짐을 뜻한다.", answer: false, note: "가족이 함께 모이는 것(团圆)을 뜻합니다." }],
    think: "추석의 송편과 중추절의 월병을 비교해 봅시다.",
  },
  {
    id: "guoqing", category: "festivals", title: "국경절", native: "{国庆节|Guó qìng Jié}", when: "10월 1일",
    summary: "1949년 10월 1일 중화인민공화국 수립을 기념하는 날입니다. 10월 1일부터 일주일 가까이 쉬는 연휴가 이어집니다.",
    points: ["긴 연휴를 黄金周(황금 연휴)라고 부르기도 합니다.", "연휴에 여행하는 사람이 많아 관광지와 교통이 매우 붐빕니다."],
    words: words("国庆节/guó qìng jié/국경절|黄金周/huáng jīn zhōu/황금 연휴|旅游/lǚ yóu/여행하다"),
    local: "양력 10월 1일, 일주일 안팎 연휴", korea: "개천절(10월 3일)·한글날(10월 9일) 공휴일",
    quiz: [{ statement: "국경절 연휴를 黄金周라고 부르기도 한다.", answer: true }, { statement: "국경절은 음력으로 날짜를 정한다.", answer: false, note: "양력 10월 1일입니다." }],
    think: "긴 연휴가 생기면 좋은 점과 어려운 점은 무엇일까요?",
  },
  {
    id: "cuisine", category: "food", title: "지역 음식", native: "{中国菜|Zhōng guó cài}",
    summary: "땅이 넓어 지역마다 음식 재료와 맛이 다릅니다.",
    points: ["산둥(鲁菜)·쓰촨(川菜)·광둥(粤菜)·장쑤(苏菜) 요리를 흔히 4대 요리로 꼽습니다.", "쓰촨 요리는 고추와 화자오(花椒)로 맵고 얼얼한 맛(麻辣)이 특징입니다.", "북쪽은 국수·만두 같은 밀가루 음식을, 남쪽은 쌀밥을 많이 먹습니다.", "베이징의 오리구이 北京烤鸭가 유명합니다."],
    words: words("川菜/chuān cài/쓰촨 요리|麻辣/má là/맵고 얼얼한 맛|北京烤鸭/Běi jīng kǎo yā/베이징 오리구이|面条/miàn tiáo/국수"),
    local: "4대 요리, 북쪽 밀가루 음식·남쪽 쌀", korea: "지역 향토 음식(전주비빔밥 등), 밥과 반찬",
    quiz: [{ statement: "쓰촨 요리는 맵고 얼얼한 맛으로 유명하다.", answer: true }, { statement: "중국 북쪽 지역은 남쪽보다 쌀밥을 더 많이 먹는다.", answer: false, note: "북쪽은 밀가루 음식을, 남쪽은 쌀밥을 많이 먹습니다." }],
    think: "먹어 보고 싶은 중국 지역 음식을 하나 골라 까닭을 써 봅시다.",
  },
  {
    id: "tea", category: "food", title: "차 문화", native: "{茶|chá}",
    summary: "차는 중국에서 시작되어 세계로 퍼졌다고 알려져 있습니다. 녹차·홍차·우롱차 등 종류가 많습니다.",
    points: ["중국에서는 차를 녹차·백차·황차·청차(우롱차)·홍차·흑차의 6가지로 나누기도 합니다.", "항저우의 龙井茶(녹차)가 유명합니다.", "광둥 지역에는 차와 함께 딤섬을 먹는 饮茶 문화가 있습니다."],
    words: words("茶/chá/차|绿茶/lǜ chá/녹차|乌龙茶/wū lóng chá/우롱차|茶馆/chá guǎn/찻집"),
    local: "6가지 차, 龙井茶, 饮茶", korea: "녹차·전통차, 다례",
    quiz: [{ statement: "중국에서는 차를 6가지로 나누기도 한다.", answer: true }, { statement: "龙井茶는 홍차이다.", answer: false, note: "녹차입니다." }],
    think: "한국과 중국의 차 문화를 비교해 봅시다.",
  },
  {
    id: "dining", category: "food", title: "식사 예절", native: "{餐桌礼仪|cān zhuō lǐ yí}",
    summary: "중국에서는 둥근 식탁에 여러 요리를 차려 놓고 함께 덜어 먹는 경우가 많습니다.",
    points: ["식당의 둥근 식탁에는 요리를 돌려 가며 덜 수 있는 회전판이 있는 경우가 많습니다.", "젓가락을 밥에 꽂아 세우는 것은 제사를 떠올리게 해 피합니다.", "건배할 때 「干杯!」라고 말합니다."],
    words: words("筷子/kuài zi/젓가락|干杯/gān bēi/건배|请慢用/qǐng màn yòng/천천히 드세요"),
    phrase: { native: "{干杯|gān bēi}!", ko: "건배!" },
    local: "둥근 식탁, 요리를 함께 덜어 먹음", korea: "각자 밥과 국, 반찬은 함께 먹음",
    quiz: [{ statement: "중국 식당의 둥근 식탁에는 회전판이 있는 경우가 많다.", answer: true }, { statement: "젓가락을 밥에 꽂아 두는 것은 좋은 예절이다.", answer: false, note: "제사를 떠올리게 해 피합니다." }],
    think: "한국과 중국의 식사 예절에서 같은 점은 무엇일까요?",
  },
  {
    id: "greeting", category: "life", title: "인사", native: "{你好|nǐ hǎo}",
    summary: "처음 만나면 你好라고 인사하고, 악수로 인사하는 경우가 많습니다.",
    points: ["여러 사람에게는 你们好, 어른께는 높임말 您을 써서 您好라고 합니다.", "예전에는 식사했는지 묻는 「吃了吗?」가 인사로 쓰이기도 했습니다.", "헤어질 때는 再见이라고 합니다."],
    words: words("你好/nǐ hǎo/안녕하세요|您/nín/당신(높임)|谢谢/xiè xie/고맙습니다|再见/zài jiàn/안녕히 가세요"),
    phrase: { native: "{认识你很高兴|rèn shi nǐ hěn gāo xìng}。", ko: "만나서 반가워요." },
    local: "你好·您好, 악수", korea: "안녕하세요, 고개 숙여 인사",
    quiz: [{ statement: "您은 你를 높여 부르는 말이다.", answer: true }, { statement: "중국에서는 처음 만날 때 큰절을 한다.", answer: false, note: "악수나 가벼운 목례로 인사합니다." }],
    think: "한국어와 중국어의 인사말을 상황에 따라 비교해 봅시다.",
  },
  {
    id: "numbers", category: "life", title: "숫자와 선물 예절", native: "{送礼|sòng lǐ}",
    summary: "중국에서는 발음이 비슷한 말에 빗대어 좋은 뜻이나 나쁜 뜻을 담는 경우가 많습니다.",
    points: ["숫자 8(八 bā)은 ‘돈을 벌다(发 fā)’와 발음이 비슷해 좋아하고, 4(四 sì)는 ‘죽다(死 sǐ)’와 비슷해 꺼립니다.", "시계를 선물하는 것(送钟 sòng zhōng)은 ‘임종을 지키다(送终 sòng zhōng)’와 발음이 같아 피합니다.", "배(梨 lí)를 나누어 먹는 것은 ‘헤어짐(分离 fēn lí)’과 발음이 비슷해 피하기도 합니다.", "붉은색은 기쁨과 행운을 뜻해 명절과 결혼식에 많이 씁니다."],
    words: words("送礼/sòng lǐ/선물하다|红色/hóng sè/붉은색|吉利/jí lì/길하다, 운이 좋다"),
    local: "8을 좋아함, 시계 선물을 피함, 붉은색", korea: "4를 꺼림(엘리베이터 F층), 칼·신발 선물을 꺼리는 속설",
    quiz: [{ statement: "중국에서는 숫자 8을 좋아한다.", answer: true }, { statement: "중국에서 시계는 좋은 선물로 여긴다.", answer: false, note: "送钟이 送终(임종을 지키다)과 발음이 같아 피합니다." }],
    think: "한국에도 발음 때문에 꺼리거나 좋아하는 것이 있을까요?",
  },
  {
    id: "mobile", category: "life", title: "모바일 생활", native: "{手机支付|shǒu jī zhī fù}",
    summary: "중국에서는 휴대 전화로 QR 코드를 찍어 돈을 내는 모바일 결제가 널리 쓰입니다.",
    points: ["식당·시장·교통 요금까지 QR 코드(二维码)로 냅니다.", "배달 음식(外卖)과 공유 자전거(共享单车)도 흔히 씁니다."],
    words: words("手机/shǒu jī/휴대 전화|支付/zhī fù/돈을 내다|外卖/wài mài/배달 음식|二维码/èr wéi mǎ/QR 코드"),
    local: "QR 코드 모바일 결제, 外卖·공유 자전거", korea: "카드·간편 결제, 배달 앱",
    quiz: [{ statement: "중국에서는 QR 코드로 돈을 내는 모바일 결제가 널리 쓰인다.", answer: true }, { statement: "外卖는 가게 안에서 먹는 음식이다.", answer: false, note: "배달 음식입니다." }],
    think: "모바일 결제가 널리 쓰이면 좋은 점과 걱정되는 점은 무엇일까요?",
  },
  {
    id: "calligraphy", category: "tradition", title: "서예", native: "{书法|shū fǎ}",
    summary: "붓으로 한자를 아름답게 쓰는 예술로, 오랜 역사를 지니고 있습니다.",
    points: ["붓(笔)·먹(墨)·종이(纸)·벼루(砚)를 文房四宝라고 합니다.", "동진의 王羲之(왕희지)는 ‘서성(书圣)’으로 불립니다."],
    words: words("书法/shū fǎ/서예|毛笔/máo bǐ/붓|文房四宝/wén fáng sì bǎo/문방사우"),
    local: "书法, 文房四宝, 왕희지", korea: "서예, 문방사우, 김정희의 추사체",
    quiz: [{ statement: "文房四宝는 붓·먹·종이·벼루이다.", answer: true }, { statement: "왕희지는 그림으로 이름난 화가이다.", answer: false, note: "서예가로, ‘서성(书圣)’이라 불립니다." }],
    think: "한글 서예와 한자 서예는 어떻게 다를까요?",
  },
  {
    id: "jingju", category: "tradition", title: "경극", native: "{京剧|jīng jù}",
    summary: "노래·대사·연기·무술이 어우러진 중국의 전통 연극으로, 베이징을 중심으로 발전했습니다. 2010년 유네스코 인류무형문화유산에 올랐습니다.",
    points: ["배역은 生(남자)·旦(여자)·净(얼굴에 화려한 분장을 한 남자)·丑(익살스러운 인물)으로 나눕니다.", "얼굴 분장 脸谱의 색으로 성격을 나타냅니다. 붉은색은 충성과 용기, 흰색은 교활함을 뜻하는 경우가 많습니다."],
    words: words("京剧/jīng jù/경극|脸谱/liǎn pǔ/경극 얼굴 분장"),
    local: "京剧, 脸谱로 성격 표현", korea: "판소리·탈춤·창극",
    quiz: [{ statement: "경극의 얼굴 분장을 脸谱라고 한다.", answer: true }, { statement: "경극 분장에서 흰 얼굴은 대개 충성스러운 인물을 뜻한다.", answer: false, note: "흰색은 교활한 인물, 붉은색이 충성과 용기를 뜻하는 경우가 많습니다." }],
    think: "탈춤의 탈과 경극의 脸谱를 비교해 봅시다.",
  },
  {
    id: "taiji", category: "tradition", title: "태극권", native: "{太极拳|tài jí quán}",
    summary: "천천히 부드럽게 움직이는 중국의 전통 무술로, 건강 운동으로 널리 합니다. 2020년 유네스코 인류무형문화유산에 올랐습니다.",
    points: ["아침 공원에서 태극권을 하는 사람들을 흔히 볼 수 있습니다.", "광장에서 음악에 맞춰 여럿이 추는 广场舞도 인기입니다."],
    words: words("太极拳/tài jí quán/태극권|功夫/gōng fu/쿵후(무술)|广场舞/guǎng chǎng wǔ/광장 춤"),
    local: "공원의 太极拳·广场舞", korea: "태권도, 공원 운동 기구",
    quiz: [{ statement: "태극권은 빠르고 강하게 움직이는 무술이다.", answer: false, note: "천천히 부드럽게 움직입니다." }, { statement: "广场舞는 광장에서 여럿이 추는 춤이다.", answer: true }],
    think: "태극권과 태권도를 비교해 봅시다.",
  },
  {
    id: "zodiac", category: "tradition", title: "12띠", native: "{十二生肖|shí èr shēng xiào}",
    summary: "태어난 해를 12가지 동물에 빗대는 풍습으로, 한국과 같은 동물을 씁니다.",
    points: ["쥐·소·호랑이·토끼·용·뱀·말·양·원숭이·닭·개·돼지 순서입니다.", "띠는 음력 설을 기준으로 바뀐다고 봅니다.", "띠를 물을 때 「你属什么?」라고 합니다."],
    words: words("生肖/shēng xiào/띠|属/shǔ/(띠가) ~이다|龙/lóng/용"),
    phrase: { native: "{你属什么|nǐ shǔ shén me}?", ko: "너는 무슨 띠니?" },
    local: "12띠, 음력 설 기준", korea: "같은 12띠",
    quiz: [{ statement: "중국과 한국의 12띠 동물은 같다.", answer: true }, { statement: "12띠의 첫째 동물은 소이다.", answer: false, note: "첫째는 쥐입니다." }],
    think: "나의 띠를 중국어로 소개해 봅시다.",
  },
  {
    id: "changcheng", category: "heritage", title: "만리장성", native: "{长城|Cháng chéng}",
    summary: "북쪽 민족의 침입을 막으려고 여러 왕조에 걸쳐 쌓은 성벽입니다. 1987년 유네스코 세계유산에 올랐습니다.",
    points: ["지금 남아 있는 벽돌 성벽은 대부분 명나라 때 쌓았습니다.", "베이징 근처의 八达岭(바다링)이 관광지로 유명합니다."],
    words: words("长城/cháng chéng/만리장성|八达岭/Bā dá lǐng/바다링"),
    local: "여러 왕조에 걸쳐 쌓음, 명나라 벽돌 성벽", korea: "수원 화성(1997년 세계유산), 한양도성",
    quiz: [{ statement: "만리장성은 한 왕조가 한 번에 쌓았다.", answer: false, note: "여러 왕조에 걸쳐 쌓았습니다." }, { statement: "만리장성은 유네스코 세계유산이다.", answer: true }],
    think: "수원 화성과 만리장성은 무엇을 지키려고 쌓았을까요?",
  },
  {
    id: "gugong", category: "heritage", title: "고궁(자금성)", native: "{故宫|Gù gōng}",
    summary: "명·청 시대 황제가 살던 궁궐로 베이징 한가운데에 있습니다. 1987년 유네스코 세계유산에 올랐고, 지금은 박물관(故宫博物院)입니다.",
    points: ["옛 이름은 紫禁城(자금성)입니다.", "황제를 상징하는 노란 기와가 많습니다."],
    words: words("故宫/gù gōng/고궁|紫禁城/Zǐ jìn chéng/자금성|皇帝/huáng dì/황제"),
    local: "명·청 황궁, 노란 기와", korea: "경복궁·창덕궁(1997년 세계유산) 등 조선 궁궐",
    quiz: [{ statement: "고궁의 옛 이름은 자금성이다.", answer: true }, { statement: "고궁은 당나라 황제의 궁궐이다.", answer: false, note: "명·청 시대 황제의 궁궐입니다." }],
    think: "경복궁과 고궁의 지붕 색을 비교해 봅시다.",
  },
  {
    id: "inventions", category: "heritage", title: "4대 발명", native: "{四大发明|sì dà fā míng}",
    summary: "중국에서 비롯되어 세계에 큰 영향을 준 네 가지 발명을 말합니다.",
    points: ["종이 만드는 법·인쇄술·화약·나침반을 꼽습니다.", "후한의 蔡伦(채륜)이 종이 만드는 법을 개선했다고 전해집니다."],
    words: words("四大发明/sì dà fā míng/4대 발명|造纸术/zào zhǐ shù/종이 만드는 법|火药/huǒ yào/화약|指南针/zhǐ nán zhēn/나침반"),
    local: "종이·인쇄술·화약·나침반", korea: "금속 활자 인쇄본 직지(1377), 한글, 측우기",
    quiz: [{ statement: "중국의 4대 발명에는 나침반이 들어간다.", answer: true }, { statement: "4대 발명은 종이·인쇄술·화약·망원경이다.", answer: false, note: "망원경이 아니라 나침반입니다." }],
    think: "한국의 과학 문화유산 가운데 소개하고 싶은 것은 무엇인가요?",
  },
  {
    id: "panda", category: "heritage", title: "판다", native: "{大熊猫|dà xióng māo}",
    summary: "쓰촨성 등 중국 서남부 산지에 사는 동물로, 중국을 대표하는 동물로 사랑받습니다.",
    points: ["주로 대나무를 먹습니다.", "우호의 뜻으로 다른 나라에 보내기도 합니다."],
    words: words("大熊猫/dà xióng māo/판다|竹子/zhú zi/대나무|四川/Sì chuān/쓰촨"),
    local: "쓰촨의 판다, 대나무", korea: "상징 동물로 호랑이를 꼽음",
    quiz: [{ statement: "판다는 주로 대나무를 먹는다.", answer: true }, { statement: "판다는 중국 동북부 평원에 산다.", answer: false, note: "서남부 산지에 삽니다." }],
    think: "한국을 대표하는 동물을 하나 골라 소개해 봅시다.",
  },
  {
    id: "regions", category: "regions", title: "중국의 지역과 언어", native: "{中国|Zhōng guó}",
    summary: "중국은 땅이 넓고, 한족과 55개 소수민족을 합해 56개 민족이 함께 삽니다. 표준어는 普通话이고 간체자를 씁니다.",
    points: ["수도는 北京이고, 上海는 가장 큰 경제 도시 가운데 하나입니다.", "광둥어처럼 지역 방언끼리는 서로 알아듣기 어려울 만큼 다른 경우도 있습니다.", "행정 구역은 성(省)·자치구·직할시 등으로 나뉩니다."],
    words: words("普通话/pǔ tōng huà/표준 중국어|汉语/Hàn yǔ/중국어|民族/mín zú/민족|方言/fāng yán/방언"),
    local: "56개 민족, 普通话·간체자", korea: "한국어, 지역 사투리",
    quiz: [{ statement: "중국은 56개 민족으로 이루어져 있다.", answer: true }, { statement: "중국 본토에서는 주로 번체자를 쓴다.", answer: false, note: "간체자를 씁니다." }],
    think: "한국의 사투리와 중국의 방언은 어떻게 다를까요?",
  },
];
