"use client";

import { useState } from "react";
import { z } from "zod";
import { Plus, Shuffle, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { HANMUN_EXAMPLES } from "@/features/hanmun/examples";
import { plainText } from "@/features/hanmun/content";
import { answerPage, escapeActivity as esc, idiomLibrary, idioms, question, sheetHeader, shuffledIndices } from "@/features/teacher-activities/content";
import { ActivityInput, ActivityLayout, ActivityReady, ActivitySheet, useActivityDraft } from "./activity-shared";
import { Card, Toggle } from "./tool-panel";

const idiomSchema = z.object({ title: z.string().max(100), answers: z.boolean(), hints: z.boolean(), items: z.array(z.object({ hanja: z.string().max(30), reading: z.string().max(50), meaning: z.string().max(300), situation: z.string().max(300), selected: z.boolean() })).max(20) });
const idiomInitial = { title: "성어로 읽는 우리 생활", answers: false, hints: true, items: idioms.map((item, i) => ({ ...item, selected: i < 3 })) };
export function HanmunIdiomsLab({ tabs }: { tabs: React.ReactNode }) { return <ActivityReady><IdiomEditor tabs={tabs} /></ActivityReady>; }
function IdiomEditor({ tabs }: { tabs: React.ReactNode }) {
  const [draft, setDraft, error] = useActivityDraft("learncraft_hanmun_idioms_v1", idiomSchema, idiomInitial);
  const chosen = draft.items.filter(item => item.selected && item.hanja.trim() && item.meaning.trim() && item.situation.trim());
  const incomplete = draft.items.filter(item => item.selected).length - chosen.length;
  const html = sheetHeader(draft.title || "성어 활용 활동지") + (draft.hints && chosen.length ? `<p style="border:1px solid #aaa;padding:3mm"><b>보기</b> ${shuffledIndices(chosen.length, 37).map(i => esc(chosen[i].hanja)).join(" · ")}</p>` : "") + chosen.map((item, i) => question(`${i + 1}. 상황에 어울리는 성어를 쓰고, 그렇게 생각한 이유를 설명해 봅시다.`, `<p>${esc(item.situation)}</p><p>성어: ________________ 독음: ________________</p>`, 2) + question("나의 경험이나 새로운 상황에 이 성어를 활용해 봅시다.", "", 2)).join("") + (draft.answers && chosen.length ? answerPage(chosen.map((item, i) => `<section style="break-inside:avoid"><h3>${i + 1}. ${esc(item.hanja)} (${esc(item.reading)})</h3><p>${esc(item.meaning)}</p><p>상황 예시: ${esc(item.situation)}</p></section>`).join("") + "<p>이유와 경험은 열린 답입니다. 성어의 뜻에 맞는지, 상황과 연결되는 근거가 있는지 확인하세요.</p>") : "");
  return <ActivityLayout subject="한문" title="성어·생활 적용 활동지" description="성어를 외우는 데서 그치지 않고 상황에 적용하고 이유를 설명하도록 구성하세요. 생활 상황 예시는 수업용으로 만든 문장입니다." tabs={tabs} error={error}><div className="grid items-start gap-5 xl:grid-cols-[380px_minmax(0,1fr)]"><div className="space-y-4"><Card title="활동 설정"><div className="space-y-3"><ActivityInput label="활동지 제목" value={draft.title} maxLength={100} onChange={title => setDraft({ ...draft, title })} /><Toggle label="성어 보기 제공" checked={draft.hints} onChange={hints => setDraft({ ...draft, hints })} /><Toggle label="교사용 참고 답안 포함" checked={draft.answers} onChange={answers => setDraft({ ...draft, answers })} /><p className="text-xs text-ink-4">{chosen.length}개 성어 · 참고 답안은 새 쪽에서 시작합니다.</p>{incomplete > 0 && <p role="status" className="text-xs text-warn">선택한 항목 중 {incomplete}개는 성어·뜻·상황을 모두 입력해야 활동지에 포함됩니다.</p>}</div></Card><Card title="성어 선택·편집"><div className="space-y-4">{draft.items.map((item, index) => {
    const update = (patch: Partial<typeof item>) => setDraft({ ...draft, items: draft.items.map((old, i) => i === index ? { ...old, ...patch } : old) });
    return <details key={index} className="rounded-xl border border-line p-3"><summary className="cursor-pointer text-sm font-bold text-ink">{item.selected ? "✓ " : ""}{item.hanja || "새 성어"} · {item.reading}</summary><div className="mt-3 space-y-3"><Toggle label="활동지에 포함" checked={item.selected} onChange={selected => update({ selected })} /><ActivityInput label="성어" value={item.hanja} maxLength={30} onChange={hanja => update({ hanja })} /><ActivityInput label="독음" value={item.reading} maxLength={50} onChange={reading => update({ reading })} /><ActivityInput label="뜻 · 교사용 답안" value={item.meaning} multiline onChange={meaning => update({ meaning })} /><ActivityInput label="생활 상황 · 학생에게 제시" value={item.situation} multiline onChange={situation => update({ situation })} /><Button variant="ghost" size="sm" onClick={() => setDraft({ ...draft, items: draft.items.filter((_, i) => i !== index) })}><Trash2 size={14} /> 이 성어 삭제</Button></div></details>;
  })}<IdiomPicker used={draft.items.map(item => item.hanja)} disabled={draft.items.length >= 20} onPick={item => setDraft({ ...draft, items: [...draft.items, { ...item, selected: true }] })} /><Button variant="secondary" size="sm" disabled={draft.items.length >= 20} onClick={() => setDraft({ ...draft, items: [...draft.items, { hanja: "", reading: "", meaning: "", situation: "", selected: true }] })}><Plus size={14} /> 직접 추가 ({draft.items.length}/20)</Button></div></Card></div><ActivitySheet id="hanmun-idioms-print" html={html} disabled={!chosen.length} /></div></ActivityLayout>;
}

/** 교과서 빈출 성어 목록에서 아직 넣지 않은 성어를 골라 붙입니다. */
function IdiomPicker({ used, disabled, onPick }: { used: string[]; disabled: boolean; onPick: (item: (typeof idiomLibrary)[number]) => void }) {
  const rest = idiomLibrary.filter(item => !used.includes(item.hanja));
  return <label className="block text-xs font-semibold text-ink-3">성어 목록에서 추가 · {rest.length}개 남음<select aria-label="성어 목록에서 추가" value="" disabled={disabled || !rest.length} className="mt-1 w-full rounded-xl border border-line bg-surface p-2 text-sm" onChange={e => { const item = rest.find(i => i.hanja === e.target.value); if (item) onPick(item); }}><option value="">{disabled ? "20개까지 넣을 수 있어요" : "성어 선택"}</option>{rest.map(item => <option key={item.hanja} value={item.hanja}>{item.hanja} {item.reading} · {item.meaning.slice(0, 24)}</option>)}</select></label>;
}

const sentenceExamples = HANMUN_EXAMPLES.flatMap(doc => doc.sentences.map(sentence => ({ source: doc.title.replace("[예시] ", ""), tokens: [...plainText(sentence.hyeonto)].filter(c => /\p{Script=Han}/u.test(c)).join(" / "), translation: sentence.literal, point: sentence.point })));
const sentenceSchema = z.object({ title: z.string().max(100), source: z.string().max(300), tokens: z.string().max(300), translation: z.string().max(300), point: z.string().max(300), answers: z.boolean(), hint: z.boolean(), seed: z.number().int().min(0).max(1000000) });
const sentenceInitial = { title: "한문 문장 재구성", ...sentenceExamples[0], answers: false, hint: true, seed: 1 };
export function HanmunSentenceLab({ tabs }: { tabs: React.ReactNode }) { return <ActivityReady><SentenceEditor tabs={tabs} /></ActivityReady>; }
function SentenceEditor({ tabs }: { tabs: React.ReactNode }) {
  const [draft, setDraft, error] = useActivityDraft("learncraft_hanmun_rebuild_v1", sentenceSchema, sentenceInitial);
  const tokens = draft.tokens.split(/[\/／]/).map(t => t.trim()).filter(Boolean);
  const valid = tokens.length >= 2 && tokens.length <= 30;
  const order = shuffledIndices(tokens.length, draft.seed);
  const html = sheetHeader(draft.title || "한문 문장 재구성") + `<p>출전: ${esc(draft.source)}</p>` + question("1. 다음 카드를 원문의 어순으로 배열해 문장을 완성하세요.", `<p style="font-size:18pt;line-height:2">${order.map(i => `<span style="display:inline-block;border:1px dashed #888;padding:2mm;margin:1mm">${esc(tokens[i])}</span>`).join(" ")}</p>${draft.hint ? `<p>뜻 힌트: ${esc(draft.translation)}</p>` : ""}`, 2) + question("2. 문장의 뜻을 쓰고, 그렇게 풀이한 근거를 설명하세요.", "", 3) + question("3. 이 문장과 연결되는 나의 경험이나 생각을 적어 보세요.") + (draft.answers ? answerPage(`<p style="font-size:18pt">${esc(tokens.join(""))}</p><p>${esc(draft.translation)}</p><p>지도 포인트: ${esc(draft.point)}</p><p>배열은 입력한 원문 어순을 기준으로 확인합니다. 경험과 생각에는 다양한 답이 가능합니다.</p>`) : "");
  return <ActivityLayout subject="한문" title="문장 재구성·어순 탐구" description="글자·어구 카드를 배열하며 원문의 구조를 살펴보세요. 교실 화면에서 함께 풀거나 카드 활동지로 인쇄할 수 있습니다." tabs={tabs} error={error}><div className="grid items-start gap-5 xl:grid-cols-[360px_minmax(0,1fr)]"><div className="space-y-4"><Card title="문장 입력"><div className="space-y-3"><label className="block text-xs font-semibold text-ink-3">예시 불러오기 · 문장과 풀이를 교체합니다<select aria-label="문장 예시" value="" className="mt-1 w-full rounded-xl border border-line bg-surface p-2 text-sm" onChange={e => { if (e.target.value !== "") setDraft({ ...draft, ...sentenceExamples[Number(e.target.value)] }); }}><option value="">예시 선택</option>{sentenceExamples.map((example, i) => <option key={i} value={i}>{example.tokens.replaceAll(" / ", "")} · {example.source}</option>)}</select></label><ActivityInput label="활동지 제목" value={draft.title} maxLength={100} onChange={title => setDraft({ ...draft, title })} /><ActivityInput label="출전" value={draft.source} onChange={source => setDraft({ ...draft, source })} /><ActivityInput label="원문 어순대로 입력 · 카드 사이를 / 로 나누세요" value={draft.tokens} multiline onChange={tokens => setDraft({ ...draft, tokens })} /><p className="text-xs text-ink-4">예: 學 / 而 / 時 / 習 / 之 · 글자 또는 어구 2~30개</p><ActivityInput label="우리말 풀이" value={draft.translation} multiline onChange={translation => setDraft({ ...draft, translation })} /><ActivityInput label="지도 포인트 · 교사용" value={draft.point} multiline onChange={point => setDraft({ ...draft, point })} /><Toggle label="문제에 뜻 힌트 제공" checked={draft.hint} onChange={hint => setDraft({ ...draft, hint })} /><Toggle label="교사용 참고 답안 포함" checked={draft.answers} onChange={answers => setDraft({ ...draft, answers })} /></div></Card></div><div className="min-w-0 space-y-4"><Card title="함께 배열하기" action={<Button variant="secondary" size="sm" disabled={!valid} onClick={() => setDraft({ ...draft, seed: (draft.seed + 1) % 1000001 })}><Shuffle size={14} /> 다시 섞기</Button>}>{valid ? <SentenceCards key={JSON.stringify([tokens, draft.seed, draft.hint, draft.translation])} tokens={tokens} order={order} hint={draft.hint ? draft.translation : ""} /> : <p role="status" className="text-sm text-ink-3">/ 로 구분한 카드 2~30개를 입력해 주세요.</p>}</Card><ActivitySheet id="hanmun-rebuild-print" html={html} disabled={!valid} /></div></div></ActivityLayout>;
}
function SentenceCards({ tokens, order, hint }: { tokens: string[]; order: number[]; hint: string }) {
  const [selected, setSelected] = useState<number[]>([]);
  const [result, setResult] = useState("");
  return <div className="space-y-4">{hint && <p className="rounded-xl bg-brand-page p-3 text-sm text-ink-2">뜻 힌트: {hint}</p>}<p className="text-xs text-ink-4">아래 카드를 순서대로 누르세요. 배열한 카드를 누르면 되돌립니다.</p><div aria-label="배열할 카드" className="flex flex-wrap gap-2">{order.map(i => <Button key={i} variant="secondary" disabled={selected.includes(i)} aria-label={`${i + 1}번 카드 ${tokens[i]}`} onClick={() => { setSelected([...selected, i]); setResult(""); }} className="min-w-12 text-xl">{tokens[i]}</Button>)}</div><div aria-label="내가 배열한 문장" className="flex min-h-20 flex-wrap gap-2 rounded-xl border border-dashed border-brand/40 bg-brand-page p-3">{selected.map((i, position) => <Button key={i} variant="secondary" aria-label={`${position + 1}번째 ${tokens[i]} 되돌리기`} onClick={() => { setSelected(selected.filter(j => j !== i)); setResult(""); }} className="text-xl">{tokens[i]}</Button>)}</div><div className="flex flex-wrap gap-2"><Button disabled={selected.length !== tokens.length} onClick={() => setResult(selected.every((index, i) => tokens[index] === tokens[i]) ? "원문 어순과 같아요. 이제 풀이의 근거를 설명해 보세요." : "원문 어순과 달라요. 어휘의 관계를 생각하며 다시 배열해 보세요.")}>배열 확인</Button><Button variant="ghost" onClick={() => { setSelected([]); setResult(""); }}>배열 비우기</Button></div><p role="status" className="text-sm font-semibold text-brand-dark">{result}</p></div>;
}
